### PR TITLE
feat: generalize ResponseM to any MonadAff

### PR DESCRIPTION
**Pull request by cakekindel**

### CODE REVIEW

**Comment by f-f** [comment]
@cakekindel what's the usecase for this?

**Comment by cakekindel** [comment]
I noticed that `Response` (and maybe some other structures) are generic over any `MonadAff` and am running HTTPurple in a custom pipe-based MTL, and figured this would improve the UX a bit.

See [`CustomStack`](https://github.com/sigma-andex/purescript-httpurple/pull/16/files#diff-005ab5761a09eca3a7564a78f726effa60945fe1780f18c924701976fd0cd2da) for the concrete value-add.

I removed ResponseM because it's not _super_ useful anymore but this change does not have to be breaking since it can easily maintain the previous API while just adding the general `server'` function I wrote.

_Note that there has also been an open issue in httpure for several years if you want a little more context: [#134](https://github.com/citizennet/purescript-httpure/issues/134)_

**Comment by sigma-andex** [comment]
thx @cakekindel , currently on vacation. Will have a look at it next week.

**Comment by EmpiricEmpire** [comment]
> Will have a look at it next week.

Which one, is it the week on September 16 or the one on October 7-th?

**Comment by cakekindel** [comment]
For sure!

**Comment by cakekindel** [comment]
I don't know how the tests ever passed - 2 main issues:
1. `mockResponse` didn't implement `Stream#write` correctly, so the tests that tried to write to those objects always timed out. Replaced the record with a `MockResponse` class extending `http.OutgoingMessage`
1. **all** tests that ran `serve` had race conditions where requests were issued before the server was actually running. For some, I used a `serveAwaitReady` function that resolves an `Aff` with `{onStarted :: Maybe (Effect Unit)}`. For others that already specified that, I just did the naiive thing of spinning until a request can connect

**Comment by cakekindel** [comment]
just noticed my git & gpg emails mismatched, force push was just changing the committer email

**Review by sigma-andex — APPROVED** [review]

**Comment by sigma-andex** [comment]
@cakekindel awesome! thanks! 

@f-f I don't know what the current process is to publish a new version with the new registry.

**Comment by f-f** [comment]
@sigma-andex if you cut a new tag it should be picked up by the registry, but switching out the `spago.dhall` with a `spago.yaml` should be good for future proofing

**Comment by f-f** [comment]
The registry currently has a cronjob to pick up all legacy packages once a day, but using `spago publish` will publish it immediately

**Pull request merged**
